services:
  seerrbridge:
    image: ghcr.io/woahai321/seerrbridge:latest
    container_name: seerrbridge
    ports:
      - "8777:8777"
    env_file:
      - ./.env
    volumes:
      - shared_logs:/app/logs
      - ./.env:/app/.env
      - ./screenshots:/app/screenshots
    restart: unless-stopped
    command: >
      sh -c "
        cat /app/.env > /dev/null && 
        echo 'Starting SeerrBridge with refreshed env' &&
        uvicorn main:app --host 0.0.0.0 --port 8777
      "
    environment:
      - SCREENSHOTS_DIR=/app/screenshots
    networks:
      - seerrbridge_network

volumes:
  shared_logs:

networks:
  seerrbridge_network:
    driver: bridge
